export const TEST_CONVERSATION = [
  "Hello, this is a test conversation.",
  "You can use this to test saving without speaking.",
  "Add more lines as needed for your testing.",
  "This is the final line of the test conversation.",
  "Line 5: The quick brown fox jumps over the lazy dog.",
  "Line 6: Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "Line 7: Pellentesque habitant morbi tristique senectus et netus.",
  "Line 8: Vestibulum ante ipsum primis in faucibus orci luctus.",
  "Line 9: Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.",
  "Line 10: Sed nisi. Nulla quis sem at nibh elementum imperdiet.",
  "Line 11: Duis sagittis ipsum. Praesent mauris.",
  "Line 12: Fusce nec tellus sed augue semper porta.",
  "Line 13: Mauris massa. Vestibulum lacinia arcu eget nulla.",
  "Line 14: Class aptent taciti sociosqu ad litora torquent per conubia nostra.",
  "Line 15: In convallis, nunc vitae hendrerit cursus, enim erat dictum urna, nec dictum massa enim nec dui.",
  "Line 16: Proin ac neque rutrum, dictum massa nec, cursus enim.",
  "Line 17: Etiam porta sem malesuada magna mollis euismod.",
  "Line 18: Cras justo odio, dapibus ac facilisis in, egestas eget quam.",
  "Line 19: Morbi leo risus, porta ac consectetur ac, vestibulum at eros.",
  "Line 20: Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.",
];
